name: Release

on:
  push:

jobs:
  release-canary:
    name: Canary
    uses: jsoref/secrets-reusable-workflow/.github/workflows/release_canary.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
